import type { Car, User } from '@/types';
import { getCarImages, getAvatarImage } from '@/lib/utils/unsplash';

export const MOCK_SELLERS: User[] = [
  {
    id: 'seller-123',
    email: 'jin@k-motors.co.kr',
    fullName: 'Jin-Ho Park',
    role: 'seller',
    phone: '+82 10-1234-5678',
    location: 'Seoul, South Korea',
    businessDescription: 'Specializing in exporting premium used Hyundai and Genesis vehicles directly from Korea.',
    avatarUrl: getAvatarImage('seller-123'),
  },
  {
    id: 'seller-456',
    email: 'ade@autonaija.ng',
    fullName: 'Adebayo Okoro',
    role: 'seller',
    phone: '+234 801 234 5678',
    location: 'Lagos, Nigeria',
    businessDescription: 'Your trusted source for reliable and affordable Kia models in the heart of Lagos.',
    avatarUrl: getAvatarImage('seller-456'),
  },
  {
    id: 'seller-789',
    email: 'fatou@dakarcars.sn',
    fullName: 'Fatou Diop',
    role: 'seller',
    location: 'Dakar, Senegal',
    businessDescription: 'Importer of various Korean cars, focusing on durability for Senegalese roads.',
    avatarUrl: getAvatarImage('seller-789'),
  }
];

export const ALL_CARS: Car[] = [
  {
    id: "1",
    make: 'Hyundai',
    model: 'Grandeur',
    year: 2023,
    price: 45000,
    currency: 'USD',
    location: { city: 'Seoul', country: 'KR' },
    imageUrls: getCarImages('Hyundai', 'Grandeur', 6),
    specifications: {
      engine: '2.5L GDi',
      mileage: '11.7 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'Sedan',
    },
    description: 'A premium sedan offering unparalleled comfort and cutting-edge technology. Perfect for executive travel.',
    status: 'Active',
    dealer_id: 'seller-123',
  },
  {
    id: "2",
    make: 'Kia',
    model: 'EV6',
    year: 2024,
    price: 52000,
    currency: 'USD',
    location: { city: 'Nairobi', country: 'KE' },
    imageUrls: getCarImages('Kia', 'EV6', 6),
    specifications: {
      engine: 'Electric',
      mileage: '475 km range',
      transmission: 'Automatic',
      fuelType: 'Electric',
      bodyType: 'SUV',
    },
    description: 'Experience the future of driving with the award-winning Kia EV6. Instant acceleration and zero emissions.',
    status: 'Active',
    dealer_id: 'seller-456',
  },
  {
    id: "3",
    make: 'Genesis',
    model: 'G80',
    year: 2023,
    price: 68000,
    currency: 'USD',
    location: { city: 'Lagos', country: 'NG' },
    imageUrls: getCarImages('Genesis', 'G80', 6),
    specifications: {
      engine: '3.5L Twin-Turbo V6',
      mileage: '9.2 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'Sedan',
    },
    description: 'The Genesis G80 combines audacious design with advanced technology for a truly luxurious driving experience.',
    status: 'Active',
    dealer_id: 'seller-456',
  },
  {
    id: "4",
    make: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    price: 32000,
    currency: 'USD',
    location: { city: 'Dakar', country: 'SN' },
    imageUrls: getCarImages('Hyundai', 'Tucson', 6),
    specifications: {
      engine: '2.0L Turbo',
      mileage: '12.8 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'Robust, versatile, and packed with safety features. The Tucson is built to handle diverse terrains with ease.',
    status: 'Active',
    dealer_id: 'seller-789',
  },
  {
    id: "5",
    make: 'Kia',
    model: 'Sportage',
    year: 2023,
    price: 35000,
    currency: 'USD',
    location: { city: 'Seoul', country: 'KR' },
    imageUrls: getCarImages('Kia', 'Sportage', 6),
    specifications: {
      engine: '2.4L GDi',
      mileage: '11.2 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'Stylish, spacious, and fuel-efficient. The Sportage offers excellent value for families and adventurers alike.',
    status: 'Active',
    dealer_id: 'seller-123',
  },
  {
    id: "6",
    make: 'Hyundai',
    model: 'Sonata',
    year: 2021,
    price: 28000,
    currency: 'USD',
    location: { city: 'Lagos', country: 'NG' },
    imageUrls: getCarImages('Hyundai', 'Sonata', 6),
    specifications: {
      engine: '2.5L GDi',
      mileage: '13.6 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'Sedan',
    },
    description: 'The Hyundai Sonata delivers a smooth ride with modern features at an affordable price point.',
    status: 'Active',
    dealer_id: 'seller-456',
  },
  {
    id: "7",
    make: 'Kia',
    model: 'Sorento',
    year: 2022,
    price: 42000,
    currency: 'USD',
    location: { city: 'Nairobi', country: 'KE' },
    imageUrls: getCarImages('Kia', 'Sorento', 6),
    specifications: {
      engine: '3.5L V6',
      mileage: '10.2 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'The three-row Sorento provides ample space and comfort for large families, with powerful performance.',
    status: 'Active',
    dealer_id: 'seller-789',
  },
  {
    id: "8",
    make: 'Genesis',
    model: 'GV80',
    year: 2023,
    price: 75000,
    currency: 'USD',
    location: { city: 'Seoul', country: 'KR' },
    imageUrls: getCarImages('Genesis', 'GV80', 6),
    specifications: {
      engine: '3.5L Twin-Turbo V6',
      mileage: '8.9 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'Ultimate luxury SUV with commanding presence and state-of-the-art technology for discerning drivers.',
    status: 'Active',
    dealer_id: 'seller-123',
  },
];
