
import type { Car, User } from './types';

export const MOCK_SELLERS: User[] = [
  {
    id: 'seller-123',
    email: 'jin@k-motors.co.kr',
    fullName: 'Jin-Ho Park',
    role: 'seller',
    phone: '+82 10-1234-5678',
    location: 'Seoul, South Korea',
    businessDescription: 'Specializing in exporting premium used Hyundai and Genesis vehicles directly from Korea.',
    avatarUrl: 'https://i.pravatar.cc/150?u=seller-123',
  },
  {
    id: 'seller-456',
    email: 'ade@autonaija.ng',
    fullName: 'Adebayo Okoro',
    role: 'seller',
    phone: '+234 801 234 5678',
    location: 'Lagos, Nigeria',
    businessDescription: 'Your trusted source for reliable and affordable Kia models in the heart of Lagos.',
    avatarUrl: 'https://i.pravatar.cc/150?u=seller-456',
  },
   {
    id: 'seller-789',
    email: 'fatou@dakarcars.sn',
    fullName: 'Fatou Diop',
    role: 'seller',
    location: 'Dakar, Senegal',
    businessDescription: 'Importer of various Korean cars, focusing on durability for Senegalese roads.',
    avatarUrl: 'https://i.pravatar.cc/150?u=seller-789',
  }
];


export const ALL_CARS: Car[] = [
  {
    id: 1,
    make: 'Hyundai',
    model: 'Grandeur',
    year: 2023,
    price: 45000,
    currency: 'USD',
    location: { city: 'Seoul', country: 'KR' },
    imageUrls: ['https://picsum.photos/seed/hyundai1/800/600', 'https://picsum.photos/seed/hyundai1-a/800/600'],
    specifications: {
      engine: '2.5L GDi',
      mileage: '11.7 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'Sedan',
    },
    description: 'A premium sedan offering unparalleled comfort and cutting-edge technology. Perfect for executive travel.',
    status: 'Active',
    dealer_id: 'seller-123',
  },
  {
    id: 2,
    make: 'Kia',
    model: 'EV6',
    year: 2024,
    price: 52000,
    currency: 'USD',
    location: { city: 'Nairobi', country: 'KE' },
    imageUrls: ['https://picsum.photos/seed/kia1/800/600', 'https://picsum.photos/seed/kia1-a/800/600'],
    specifications: {
      engine: 'Electric',
      mileage: '475 km range',
      transmission: 'Automatic',
      fuelType: 'Electric',
      bodyType: 'SUV',
    },
    description: 'Experience the future of driving with the award-winning Kia EV6. Instant acceleration and zero emissions.',
    status: 'Active',
    dealer_id: 'seller-456',
  },
  {
    id: 3,
    make: 'Genesis',
    model: 'G80',
    year: 2023,
    price: 68000,
    currency: 'USD',
    location: { city: 'Lagos', country: 'NG' },
    imageUrls: ['https://picsum.photos/seed/genesis1/800/600', 'https://picsum.photos/seed/genesis1-a/800/600'],
    specifications: {
      engine: '3.5L Twin-Turbo V6',
      mileage: '9.2 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'Sedan',
    },
    description: 'The Genesis G80 combines audacious design with advanced technology for a truly luxurious driving experience.',
    status: 'Active',
    dealer_id: 'seller-456',
  },
  {
    id: 4,
    make: 'SsangYong',
    model: 'Torres',
    year: 2023,
    price: 38000,
    currency: 'USD',
    location: { city: 'Dakar', country: 'SN' },
    imageUrls: ['https://picsum.photos/seed/ssangyong1/800/600'],
    specifications: {
      engine: '1.5L Turbo GDi',
      mileage: '11.2 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'Rugged yet refined, the SsangYong Torres is the perfect companion for both city streets and off-road adventures.',
    status: 'Active',
    dealer_id: 'seller-789',
  },
  {
    id: 5,
    make: 'Hyundai',
    model: 'Palisade',
    year: 2024,
    price: 55000,
    currency: 'USD',
    location: { city: 'Johannesburg', country: 'ZA' },
    imageUrls: ['https://picsum.photos/seed/hyundai2/800/600'],
    specifications: {
      engine: '3.8L V6',
      mileage: '10.5 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'A spacious and luxurious 3-row SUV for the whole family, packed with safety and convenience features.',
    status: 'Pending',
    dealer_id: 'seller-123',
  },
  {
    id: 6,
    make: 'Kia',
    model: 'Seltos',
    year: 2023,
    price: 29000,
    currency: 'USD',
    location: { city: 'Accra', country: 'GH' },
    imageUrls: ['https://picsum.photos/seed/kia2/800/600'],
    specifications: {
      engine: '1.6L Turbo GDi',
      mileage: '12.8 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'A compact SUV that doesn\'t compromise on style or performance. Perfect for urban exploration.',
    status: 'Active',
    dealer_id: 'seller-456',
  },
  {
    id: 7,
    make: 'Genesis',
    model: 'GV70',
    year: 2024,
    price: 59000,
    currency: 'USD',
    location: { city: 'Cairo', country: 'EG' },
    imageUrls: ['https://picsum.photos/seed/genesis2/800/600'],
    specifications: {
      engine: '2.5L Turbo GDi',
      mileage: '9.7 km/L',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      bodyType: 'SUV',
    },
    description: 'Athletic elegance and impressive performance define the Genesis GV70 luxury SUV.',
    status: 'Active',
    dealer_id: 'seller-123',
  },
  {
    id: 8,
    make: 'Hyundai',
    model: 'Ioniq 5',
    year: 2023,
    price: 48000,
    currency: 'USD',
    location: { city: 'Cape Town', country: 'ZA' },
    imageUrls: ['https://picsum.photos/seed/hyundai3/800/600'],
    specifications: {
      engine: 'Electric',
      mileage: '488 km range',
      transmission: 'Automatic',
      fuelType: 'Electric',
      bodyType: 'Hatchback',
    },
    description: 'Retro design meets futuristic technology in this groundbreaking electric vehicle.',
    status: 'Sold',
    dealer_id: 'seller-123',
  },
];
